# -*- coding: utf-8 -*-
"""InexGpaxGraph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h611suF_KRwQKM5nEoEHTsKuAglhU0f_
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array(["M4 Term1", "M4 Term2", "M5 Term1", "M5 Term2"])
y = np.array([2.56, 2.78, 3.56, 3.34])

plt.bar(x, y, color = "#fb4d00" ,width = 0.35)
plt.show()

ypoints = np.array([2.56, 2.78, 3.56, 3.3])

plt.plot(ypoints, marker = 'o', ms = 10)
plt.show()

xpoints = np.array(["M4 Term1","M4 Term2","M5 Term1","M5 Term2"])
ypoints = np.array([2.56, 2.78, 3.56, 3.34])

font1 = {'family':'banburi','color':'blue','size':20}
font2 = {'family':'banburi','color':'darkred','size':10}

plt.title("GPAX", fontdict = font1)

plt.plot(xpoints,ypoints, marker = 'o', ms = 10)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# import the clf () method to draw another graph on the same graph window
plt.clf()

# dummy dataset from numpy
xpoints = np.array(["M4 Term1","M4 Term2","M5 Term1","M5 Term2","M6 Term1"])
ypoints = np.array([2.56, 2.78, 3.56, 3.34, 3.11])

plt.plot(xpoints,ypoints,marker='D', mfc='Orange', mec='yellow',ms='7')

#joins the x and y values
for x,y in zip(xpoints,ypoints):

    label = "{:.2f}".format(y)

    plt.annotate(label, # this is the value which we want to label (text)
                 (x,y), # x and y is the points location where we have to label
                 textcoords="offset points",
                 xytext=(0,10), # this for the distance between the points
                 # and the text label
                 ha='center',
                 arrowprops=dict(arrowstyle="->", color='Red'))
    
font1 = {'family':'banburi','color':'blue','size':20}
font2 = {'family':'banburi','color':'darkred','size':10}

plt.title("GPAX", fontdict = font1)
plt.show()